### ISSUE TITLE
Angular 8 Issue?

### ISSUE THREAD

**Issue by RZR666** [J-Siu/ng2-simple-timer-example#2]
Package "ng2-simple-timer" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.2.0"

**Comment by J-Siu** [comment]
To enable faster update, ng2-simple-timer switched to Angular CLI starting 8.2.0 and use new repository https://github.com/J-Siu/ng2-simple-timer-lib/

Project contains both library and example.

All version < 8.2.0 are in old repository https://github.com/J-Siu/ng2-simple-timer/
